version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: to-do-list-full
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: to-do-list
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
